name: Luau Syntax Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Lua
        run: sudo apt-get update && sudo apt-get install -y lua5.1

      - name: Verify MainScript Syntax
        run: luac5.1 -p MainScript
